.gitignore, PSDepend/PSDepend.NugetPath, PSDepend/PSDepend.psm1, PSDepend/PSDependMap.psd1, PSDepend/PSDependScripts/PSGalleryNuget.ps1, PSDepend/Private/Bootstrap-Nuget.ps1, PSDepend/Private/Find-NugetPackage.ps1, PSDepend/Private/Save-NugetPackage.ps1, PSDepend/Public/Get-Dependency.ps1, PSDepend/en-US/about_PSDepend.help.txt
This dependency type does not rely on the PowerShellGet module.
Logic was added to the PSDepend.psm1 to ensure a nuget.exe is available for the dependency type.  It checks for an existing nuget.exe in your path, it checks a configurable path in PSDepend\PSDepend.NuGetPath, downloads to that path if it isn't found, and adds the parent folder to your $ENV:Path.
We currently require a Target to be specified for an installation location.  I'm torn on specifying a default for this, but would be open to it.
=> Add PSModuleNuget DependencyType

PSDepend/PSDepend.Config, PSDepend/PSDepend.psm1, PSDepend/PSDependMap.psd1, PSDepend/PSDependScripts/Git.ps1, PSDepend/Public/Get-Dependency.ps1, PSDepend/en-US/about_PSDepend.help.txt, PSDepend/en-US/about_PSDepend_Definitions.help.txt, README.md
Add Git dependency type and supporting code.
PSDepend simple syntax ( key = "string" vs. key = @{} ) will now default to GitHub repos if we see a `\`, PSGalleryModules otherwise.  This same code also allows using fully qualified git clone URLs as the name, without specifying a DependencyType.
At the moment, we use `Version` as the value for a git checkout, allowing you to checkout a specific branch, commit, or even a tag. (tags:tagname).
=> Add Git dependency type

PSDepend/PSDependScripts/FileDownload.ps1, PSDepend/PSDependScripts/Git.ps1, PSDepend/PSDependScripts/PSGalleryModule.ps1, PSDepend/PSDependScripts/PSGalleryNuget.ps1, PSDepend/Private/Get-Parameter.ps1, PSDepend/Private/Get-WebFile.ps1, PSDepend/Private/Import-PSDependModule.ps1, PSDepend/Private/Invoke-ExternalCommand.ps1, PSDepend/Public/Get-Dependency.ps1, PSDepend/Public/Get-PSDependType.ps1, PSDepend/Public/Import-Dependency.ps1, PSDepend/Public/Install-Dependency.ps1, PSDepend/Public/Invoke-PSDepend.ps1, PSDepend/Public/Test-Dependency.ps1, Tests/DependFiles/dependson.depend.psd1, Tests/DependFiles/filedownload.depend.psd1, Tests/DependFiles/git.depend.psd1, Tests/DependFiles/git.simple.depend.psd1, Tests/DependFiles/git.test.depend.psd1, Tests/DependFiles/psgallerynuget.addtopath.depend.psd1, Tests/DependFiles/psgallerynuget.depend.psd1, Tests/DependFiles/psgallerynuget.sameversion.depend.psd1, Tests/PSDepend.Tests.ps1, Tests/PSModuleGallery.Type.Tests.ps1
* Add Test-Dependency and Import-Dependency functions
* Add PSDependAction parameter to dependency scripts.  Test-Dependency, Install-Dependency, and Import-Dependency specify Test, Install, or Import, respectively. Authors implement test, install, import, and perhaps others in their dependency scripts
* Wrote some sloppy (content and organization) tests - PRs welcome!
* Fixed a variety of bugs discovered while writing tests.  Maybe write tests from the start...
* Add smarter 'tests' to git dependency type.  Now checks branch or commit against specified version.  Still need to add logic to fetch and checkout (no clone) if we find existing.  Or just kill it and re-clone/checkout...
* Added several wrapper functions to help with testing (e.g. to mock git.exe, .net things)
* Fixed some …
=> Add PSDependAction, Test/Import-Dependency

PSDepend/Private/Get-Parameter.ps1
Using sort in powershell breaks psDepend in Linux/osX as sort is a built-in command. 
Using sort-object instead resolves the issue.
=> Update Get-Parameter.ps1 - sort breaks powershell on linux

PSDepend/PSDependScripts/PSGalleryModule.ps1
Hi @RamblingCookieMonster , this is a fix for #33 
When a relative path is specified for the target of the PSGalleryModule script, the download saves at the right place, but the entry added to `$Env:PSModulePath` only uses the relative path (instead of resolving the absolute one).
A quick `(Get-Item $scope).FullName` sorts it out for me, let me know if there's unforeseen potential side effects.
This PR should automagically fix my build of SampleModule here once released: https://ci.appveyor.com/project/gaelcolas/samplemodule
=> fixing add to path when relative

PSDepend/PSDependScripts/FileSystem.ps1, PSDepend/Private/Get-TaggedDependency.ps1, PSDepend/Public/Get-Dependency.ps1, PSDepend/Public/Invoke-PSDepend.ps1, PSDepend/en-US/about_PSDepend.help.txt
Hi @RamblingCookieMonster this a patch for to fix #36 and #37.
From now these two features are available and working.
Causes were some typos in code.
I have also included `PreScripts` and `PostScripts` into the logic for _variable injection_, so you can use the `$PWD`, `$DependencyFolder` etc also in these properties.
Finally, I fixed some documentation typos.
All tests passes.
=> Patch for PreScripts and PostScripts features

PSDepend/PSDependMap.psd1, PSDepend/PSDependScripts/Npm.ps1, PSDepend/Private/Get-NodeModule.ps1, PSDepend/Private/Install-NodeModule.ps1, Tests/DependFiles/npm.depend.psd1, Tests/PSModuleGallery.Type.Tests.ps1
+ Allows users to specify node modules and install via NPM.
+ Initial work only allows users to install modules by name and version (default to latest).
+ Includes private functions for getting node modules and installing them.
+ Allows users to save globally, to the current directory, or
to a specified path.
+ Includes unit tests.
=> WIP: Initial support for node modules

PSDepend/PSDepend.psd1, PSDepend/PSDependScripts/Git.ps1, PSDepend/PSDependScripts/PSGalleryNuget.ps1
* Allows to extract a Module (similarly to github type) from a git type
* Fixed a 'bug' in PSGalleryNuget & git to Resolve Full Path of target before adding to path (problem when Path is relative in the dependency file).
Just remembered that I need to update the help. Will follow up later (either new PR if merged, or commit to this PR).
=> support Module extraction for git type

PSDepend/PSDependScripts/PSGalleryModule.ps1, PSDepend/PSDependScripts/PSGalleryNuget.ps1, PSDepend/Private/Import-PSDependModule.ps1
Without specifying a `RequiredVersion` for `Import-Module`, powershell will import the latest version (see [here](https://info.sapien.com/index.php/scripting/scripting-modules/which-version-does-import-module-import) for details).
We don't want that - we want to ensure the exact version in the `requirements.psd1` is imported.
=> fix: ensure the correct version of a module is imported

PSDepend/PSDependScripts/PSGalleryModule.ps1, Tests/DependFiles/psgallerymodule.missingrepo.depend.psd1, Tests/PSModuleGallery.Type.Tests.ps1
The existing PS commands that accept a repo (eg Install-Module)
will already throw a message saying that the repo supplied cannot
be found.
Calling `Get-PSRepository` for *each* PS repository takes approx.
3 seconds.
So given a requirement.psd1 file with 2 repositories, 6s will be
spent validating the repo exists. This time is a waste PS already
is checking for this condition.
=> improve perf - remove redundant call to Get-PSRepository

PSDepend/PSDependMap.psd1
Use `Noop.ps1` instead of `noop.ps1` to avoid issues on case-sensitive file systems.
Fixes #74
=> Use capitalized version of Noop to avoid issues on linux

PSDepend/PSDepend.psd1, PSDepend/PSDepend.psm1, PSDepend/PSDependMap.psd1, PSDepend/PSDependScripts/Git.ps1, PSDepend/PSDependScripts/GitHub.ps1, PSDepend/PSDependScripts/Npm.ps1, PSDepend/PSDependScripts/PSGalleryModule.ps1, PSDepend/PSDependScripts/Package.ps1, PSDepend/Private/Add-ToItemCollection.ps1, PSDepend/Private/Add-ToPsModulePathIfRequired.ps1, PSDepend/Private/Get-Hash.ps1, PSDepend/Private/Get-Parameter.ps1, PSDepend/Private/Get-ParameterName.ps1, PSDepend/Private/Get-ProjectDetail.ps1, PSDepend/Private/Get-PropertyOrder.ps1, PSDepend/Private/Resolve-DependScripts.ps1, PSDepend/Private/Sort-WithCustomList.ps1, PSDepend/Private/Test-PlatformSupport.ps1, PSDepend/Public/Get-PSDependType.ps1, PSDepend/Public/Invoke-DependencyScript.ps1, PSDepend/Public/Invoke-PSDepend.ps1, PSDepend/en-US/about_PSDepend_Definitions.help.txt
Starting to work on xplat support (#11).  One thing we'll need is a way to narrow down which dependency scripts support which platforms.  This is an initial, minimal-thought take on adding this to the PSDependMap schema and using that data in a few spots...
* Add supports <array of platforms> to PSDependMap
* Add supports, and supported properties to Get-PSDependType output
* Skip invocation of dependency scripts that do not support the current platform
Currently we do not fail all dependencies, we simply skip unsupported dependencies - open to failing all the things instead
Hit me up if you have any ideas or concerns!  Will leave this open a few days.
=> WIP: Add supported platforms handling

PSDepend/PSDependScripts/PSGalleryModule.ps1
There are several parameters which Install-Module only supports
from a specific version onwards.
This adds a logic to remove any parameter which is not available
in the current version **and** is not mandatory.
=> Added conditional logic for removing parameter

build.ps1, psake.ps1
* allows build to run locally without throwing errors if user is not admin
* use `Convert-Path` to remove any PSDrive from Pester output file (eg: `Project:\PSDepend`)
=> Fix local build environment

.vscode/settings.json, Examples/Install-PSDepend.ps1, Examples/ModuleDependencies.md, PSDepend/PSDependScripts/Git.ps1, PSDepend/Private/Add-ToItemCollection.ps1, PSDepend/Private/Bootstrap-Nuget.ps1, Tests/DependFiles/filedownload.depend.psd1, Tests/DependFiles/filesystem.depend.psd1, Tests/DependFiles/git.depend.psd1, Tests/DependFiles/psgallerymodule.addtopath.depend.psd1, Tests/DependFiles/psgallerymodule.latestaddtopath.depend.psd1, Tests/DependFiles/psgallerynuget.addtopath.depend.psd1, Tests/DependFiles/psgallerynuget.depend.psd1, Tests/DependFiles/psgallerynuget.latestaddtopath.depend.psd1, Tests/DependFiles/psgallerynuget.latestversion.depend.psd1, Tests/DependFiles/psgallerynuget.sameversion.depend.psd1, Tests/DependFiles/savemodule.depend.psd1, Tests/PSModuleGallery.Type.Tests.ps1, build.ps1, psake.ps1
This PR adds support for using this module on PowerShell Core (v6) on other OS than Windows.
This PR is based on #78
This PR does not try to modify any behavior described in `PSDependMap.psd1`
=> Featue: Support Powershell Core

PSDepend/PSDependScripts/PSGalleryModule.ps1
`AllowClobber` was added in at a different place to `$params`
This broke the logic for conditionally removing parameter which are not supported.
continues #77
=> [BUG] Moved where `AllowClobber` is added to splat variable

PSDepend/Private/Get-WebFile.ps1
PSDepends thrown the following error when using an HTTPS download link:
```
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
At C:\Users\randr\Documents\WindowsPowerShell\Modules\PSDepend\0.2.0\Private\Get-WebFile.ps1:7 char:5
+     $webclient.DownloadFile($URL, $Path)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : WebException
```
The PSDepends configuration used:
```
@{
PSDependOptions = @{
AddToPath = $True
Target = 'BuildOutput\Modules'
Parameters = @{
}
}
#...
#File Download
'https://github.com/AutomatedLab/AutomatedLab/raw/develop/LabSources/Tools/WinSATAPI.dll' = @{
DependencyType = 'FileDownload'
Target = …
```
=> Support for TLS1.2

PSDepend/PSDependScripts/Git.ps1, PSDepend/PSDependScripts/PSGalleryModule.ps1, PSDepend/en-US/about_PSDepend.help.txt, PSDepend/en-US/about_PSDepend_Definitions.help.txt
Finally rebased the changed I made in #59 fixing #47 and #55.
It should be a non-breaking change.
This will remove the Repository parameter to the Install/Find/Save module calls, effectively relying on the currently registered PSRepositories. (I still think that should be default behaviour, but it would then be a breaking change).
=> Rebased: Remove .exe dependency for Git and allow Repository to be $Null to rely on registered ones

PSDepend/PSDependMap.psd1, PSDepend/PSDependScripts/PSGalleryModule.ps1, PSDepend/PSDependScripts/PSGalleryNuget.ps1, PSDepend/Private/Find-NugetPackage.ps1, PSDepend/Public/Get-Dependency.ps1, PSDepend/Public/Invoke-PSDepend.ps1, Tests/DependFiles/psgallerymodule.multiplecredentials.depend.psd1, Tests/DependFiles/psgallerymodule.withcredentials.depend.psd1, Tests/DependFiles/psgallerynuget.latestversionwithcredential.depend.psd1, Tests/DependFiles/psgallerynuget.withcredentials.psd1, Tests/DependFiles/savemodule.withcredentials.depend.psd1, Tests/PSModuleGallery.Type.Tests.ps1
This is an update of the functionality written by @alphakilo45 to address issue #94 .
As part of this change I also modified barriers to using the nuget based code cross platform. I have successfully tested both PSGalleryModule and PSGalleryNuget dependencies in PowerShell Core on OSX.
=> Support credentials for PSGalleryModule and PSGalleryNuget

PSDepend/PSDependScripts/PSGalleryModule.ps1
Resolves #66
* Issue only observed when module version format is inconsistent: (eg: [major].[minor] in one version and semver in another)
=> Explicitly cast versions for comparison

PSDepend/PSDependScripts/PSGalleryModule.ps1, PSDepend/Private/SemanticVersion.ps1, Tests/DependFiles/psgallerymodule.AllowPrerelease.depend.psd1, Tests/DependFiles/psgallerymodule.SameSemanticVersion.depend.psd1, Tests/PSModuleGallery.Type.Tests.ps1, build.ps1
This fixes #68.
The code of System.Management.Automation.SemanticVersion has been taken from PowerShell 7 and slightly modified to run in PowerShell 5.
Setting Pester version to 4.10.1 as the tests are not working with Pester 5.
=> Adding support for pre-releases and semantic versioning (PowerShell Gallery)

PSDepend/PSDependScripts/Nuget.ps1
Previously only a Nuget package with a dll was supported. This adds support for an exe in a Nuget package. Also changed the parameter $Name to be more syntactically correct since exe and dll is now supported.
@scrthq I would appreciate you taking a look to see if anything needs changed.
=> Add support for exe in nuget package

PSDepend/Private/SemanticVersion.ps1
add ps version constraint for semanticversion class to be lower than psv6 or else we have a conflict with native class.
We have this error in Azure DevOps pipelines since the new code:
```
Line |
154 |    Import-Module PSDepend
|    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Failed to import function /agent/_work/1/s/out/modulecache/PSDepend/0.3.4/Private/SemanticVersion.ps1: (15,68): error CS0436: The type 'SemanticVersion' in '' conflicts with the imported type 'SemanticVersion' in 'System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Using the type defined in ''.     public sealed class SemanticVersion : IComparable, IComparable<SemanticVersion>, IEquatable<SemanticVersion> …
```
=> add ps version constraint for semanticversion class

PSDepend/PSDependMap.psd1, PSDepend/PSDependScripts/Git.ps1
With regard to  #59 
By adjusting the reference to the path variable and adjusting the support property in the [DependMap.psd1](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/PSDependMap.psd1) file, the Dependency Handler Git can also run on *nix systems.
=> Git Dependency Handler adapted

PSDepend/Public/Invoke-PSDepend.ps1, README.md
This came from #94 
* Added documentation for the Credential dependency property and the Credentials parameter as I couldn't find any information on it;
* Clarified the function based help for Invoke-PSDepend on the Credentials parameter;
* Whitespace changes (tabs to spaces for the code added to Invoke-PSDepend to support the Credentials parameter);
=> Add Credential Help

PSDepend/PSDependScripts/PSGalleryModule.ps1
Trying to use PSDepend with UniversalDashboard module, but PSRepositoryModule dependency type doesn't support AcceptLicense.
```
WARNING: Parameter [AcceptLicense] with value [True] is not a valid parameter for [PSGalleryModule], ignoring.  Valid params: [AllowClobber Dependency Import PSDependAction Repository SkipPublisherCheck]
```
This PR adds in a AcceptLicense parameter to PSGalleryModule, which defaults to true.
```powershell
@{
Pester = 'latest'
UniversalDashboard = @{
Name = 'UniversalDashboard'
DependencyType = 'PSGalleryModule'
Parameters = @{
AcceptLicense = $true
}
Version = '2.7'
}
}
```
=> Add AcceptLicense for PSRepositoryModule

PSDepend/PSDepend.psm1
Simple change so that Bootstrap-Nuget runs on e.g. PowerShell 7 on a Windows machine.
=> Made Bootstrap-Nuget also run on PS Core+Windows
